### PR TITLE
Added original transaction to utxo actions, needed to sign

### PR DESCRIPTION
**Pull request by icellan**

### CODE REVIEW

**Review by mrz1836 — COMMENTED** [review]
I would make `Transaction` a private field, not a public virtual field

**Comment by mrz1836** [comment]
Also failed the test above ^^

**Comment by icellan** [comment]
> I would make `Transaction` a private field, not a public virtual field

It needs to be public to return from the rest endpoints and graphql

**Comment by mrz1836** [comment]
@icellan tests failed: https://github.com/BuxOrg/bux/runs/7074303576?check_suite_focus=true

**Pull request closed without merging**
